services:
  apigateway:
    build:
      context: . 
      dockerfile: images/apigateway/Dockerfile
    ports:
      - "8080:8080"
  laneservice:
    build:
      context: . 
      dockerfile: images/lane/Dockerfile
    ports:
      - "8082:8082"