// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: lanesvc.proto

package lane

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Network struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Logo   string `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
}

func (x *Network) Reset() {
	*x = Network{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lanesvc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_lanesvc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_lanesvc_proto_rawDescGZIP(), []int{0}
}

func (x *Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Network) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Network) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

type NetworksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Networktype string `protobuf:"bytes,1,opt,name=networktype,proto3" json:"networktype,omitempty"`
}

func (x *NetworksRequest) Reset() {
	*x = NetworksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lanesvc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworksRequest) ProtoMessage() {}

func (x *NetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lanesvc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworksRequest.ProtoReflect.Descriptor instead.
func (*NetworksRequest) Descriptor() ([]byte, []int) {
	return file_lanesvc_proto_rawDescGZIP(), []int{1}
}

func (x *NetworksRequest) GetNetworktype() string {
	if x != nil {
		return x.Networktype
	}
	return ""
}

type NetworksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Networks []*Network `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	Err      string     `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
}

func (x *NetworksReply) Reset() {
	*x = NetworksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lanesvc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworksReply) ProtoMessage() {}

func (x *NetworksReply) ProtoReflect() protoreflect.Message {
	mi := &file_lanesvc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworksReply.ProtoReflect.Descriptor instead.
func (*NetworksReply) Descriptor() ([]byte, []int) {
	return file_lanesvc_proto_rawDescGZIP(), []int{2}
}

func (x *NetworksReply) GetNetworks() []*Network {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *NetworksReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_lanesvc_proto protoreflect.FileDescriptor

var file_lanesvc_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x61, 0x6e, 0x65, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x49, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f,
	0x67, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x22, 0x33,
	0x0a, 0x0f, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x4a, 0x0a, 0x0d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x08, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x52, 0x08, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x45, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x72, 0x72, 0x32,
	0x3c, 0x0a, 0x04, 0x4c, 0x61, 0x6e, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x2f, 0x5a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x6e, 0x6b,
	0x69, 0x2d, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x62, 0x2f, 0x6c, 0x61, 0x6e, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lanesvc_proto_rawDescOnce sync.Once
	file_lanesvc_proto_rawDescData = file_lanesvc_proto_rawDesc
)

func file_lanesvc_proto_rawDescGZIP() []byte {
	file_lanesvc_proto_rawDescOnce.Do(func() {
		file_lanesvc_proto_rawDescData = protoimpl.X.CompressGZIP(file_lanesvc_proto_rawDescData)
	})
	return file_lanesvc_proto_rawDescData
}

var file_lanesvc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lanesvc_proto_goTypes = []interface{}{
	(*Network)(nil),         // 0: pb.Network
	(*NetworksRequest)(nil), // 1: pb.NetworksRequest
	(*NetworksReply)(nil),   // 2: pb.NetworksReply
}
var file_lanesvc_proto_depIdxs = []int32{
	0, // 0: pb.NetworksReply.networks:type_name -> pb.Network
	1, // 1: pb.Lane.Networks:input_type -> pb.NetworksRequest
	2, // 2: pb.Lane.Networks:output_type -> pb.NetworksReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lanesvc_proto_init() }
func file_lanesvc_proto_init() {
	if File_lanesvc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lanesvc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Network); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lanesvc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lanesvc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lanesvc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lanesvc_proto_goTypes,
		DependencyIndexes: file_lanesvc_proto_depIdxs,
		MessageInfos:      file_lanesvc_proto_msgTypes,
	}.Build()
	File_lanesvc_proto = out.File
	file_lanesvc_proto_rawDesc = nil
	file_lanesvc_proto_goTypes = nil
	file_lanesvc_proto_depIdxs = nil
}
